import { MediaFormat, Prisma } from "@prisma/client";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { prisma } from "@/src/lib/prisma";

const apply = process.argv.includes("--apply");
type Sheet = { slug: string; nameFr: string; watchDisplayName: string; equipment: string[]; pattern: string; type: string; primary: string[]; secondary: string[]; why: string; steps: string[]; breathing: string; tempo: { value: string; detail: string[] }; tips: string[]; mistakes: string[] };
const sheets: Sheet[] = [
  { slug:"barbell-lunge",nameFr:"Fente avec barre",watchDisplayName:"Fente barre",equipment:["Barre olympique","Rack"],pattern:"Fente / flexion de jambe",type:"Polyarticulaire",primary:["Quadriceps","Grand fessier"],secondary:["Adducteurs","Ischio-jambiers","Mollets","Érecteurs du rachis"],why:"La fente avec barre développe les jambes de façon unilatérale. Elle renforce les quadriceps et les fessiers tout en demandant stabilité du bassin, contrôle du genou et équilibre.",steps:["Placez la barre sur le haut du dos et adoptez une posture haute.","Faites un pas contrôlé vers l’avant ou l’arrière selon votre variante.","Descendez en gardant le genou dans l’axe du pied.","Poussez dans le sol pour revenir sans perdre l’équilibre.","Alternez les côtés avec la même amplitude."],breathing:"Inspirez pendant la descente. Expirez en repoussant le sol.",tempo:{value:"3 - 1 - 2",detail:["3 secondes de descente","1 seconde de contrôle","2 secondes de remontée"]},tips:["Gardez le tronc stable.","Choisissez une longueur de pas confortable.","Contrôlez le genou avant.","Réduisez la charge avant de réduire la qualité."],mistakes:["Genou qui s’effondre vers l’intérieur.","Buste qui bascule.","Pas trop court ou trop long.","Rebond en position basse."] },
  { slug:"barbell-hip-thrust",nameFr:"Hip thrust avec barre",watchDisplayName:"Hip thrust",equipment:["Barre olympique","Banc","Protection de barre"],pattern:"Extension de hanche",type:"Polyarticulaire",primary:["Grand fessier"],secondary:["Ischio-jambiers","Moyen fessier","Adducteurs","Érecteurs du rachis"],why:"Le hip thrust cible fortement le grand fessier avec une extension de hanche horizontale. Il permet de charger progressivement le mouvement tout en travaillant la stabilité du bassin.",steps:["Placez le haut du dos contre le banc et la barre au pli des hanches.","Ancrez les pieds au sol, largeur de bassin.","Gainez et poussez les hanches vers le plafond.","Marquez une contraction fessière sans cambrer le bas du dos.","Redescendez sous contrôle."],breathing:"Expirez pendant l’extension de hanche. Inspirez au retour.",tempo:{value:"2 - 1 - 3",detail:["2 secondes de poussée","1 seconde de contraction","3 secondes de retour"]},tips:["Gardez les côtes basses.","Cherchez la poussée par les talons.","Protégez les hanches avec un pad.","Gardez le regard devant vous."],mistakes:["Hyperextension lombaire.","Pieds trop éloignés.","Barre qui roule.","Retour trop rapide."] },
  { slug:"romanian-deadlift",nameFr:"Soulevé de terre roumain",watchDisplayName:"SDT roumain",equipment:["Barre olympique","Disques"],pattern:"Charnière de hanche",type:"Polyarticulaire",primary:["Ischio-jambiers","Grand fessier"],secondary:["Érecteurs du rachis","Adducteurs"],why:"Le soulevé de terre roumain développe la chaîne postérieure en mettant l’accent sur l’étirement des ischio-jambiers et l’extension de hanche, avec une colonne maintenue stable.",steps:["Tenez la barre près des cuisses, pieds largeur de hanches.","Déverrouillez légèrement les genoux.","Repoussez les hanches loin vers l’arrière en gardant la barre proche des jambes.","Arrêtez-vous lorsque l’étirement reste contrôlé et que le dos reste neutre.","Poussez les hanches vers l’avant pour revenir debout."],breathing:"Inspirez et gainez avant la descente. Expirez en remontant.",tempo:{value:"3 - 1 - 2",detail:["3 secondes de descente","1 seconde d’étirement","2 secondes de remontée"]},tips:["Gardez la barre proche du corps.","Conservez le cou dans l’axe.","Cherchez l’étirement des ischios.","Utilisez des sangles seulement si la prise limite le mouvement."],mistakes:["Arrondir le dos.","Transformer le mouvement en squat.","Éloigner la barre des jambes.","Descendre plus bas que votre contrôle." ] },
  { slug:"leg-press",nameFr:"Presse à jambes",watchDisplayName:"Presse à jambes",equipment:["Presse à jambes"],pattern:"Poussée de jambes",type:"Polyarticulaire",primary:["Quadriceps"],secondary:["Adducteurs","Mollets","Grand fessier","Ischio-jambiers"],why:"La presse à jambes permet de travailler les quadriceps avec une trajectoire guidée. Elle facilite un volume de travail important lorsque le bassin et les genoux restent correctement placés.",steps:["Réglez le siège pour garder le bassin en contact avec le dossier.","Placez les pieds à largeur confortable sur la plateforme.","Déverrouillez puis descendez avec contrôle.","Gardez les genoux dans l’axe des pieds.","Poussez la plateforme sans verrouiller brutalement les genoux."],breathing:"Inspirez pendant la descente. Expirez pendant la poussée.",tempo:{value:"3 - 1 - 2",detail:["3 secondes de descente","1 seconde de contrôle","2 secondes de poussée"]},tips:["Gardez les talons en contact.","Choisissez une profondeur contrôlée.","Ajustez la position des pieds à votre mobilité.","Réglez les sécurités avant la série."],mistakes:["Décoller le bassin du dossier.","Genoux qui rentrent.","Verrouillage brusque des genoux.","Charge trop lourde."] },
  { slug:"hanging-leg-raise",nameFr:"Élévation des jambes suspendu",watchDisplayName:"Leg raise suspendu",equipment:["Barre de traction","Poids du corps"],pattern:"Flexion de hanche et gainage",type:"Polyarticulaire",primary:["Droit de l’abdomen"],secondary:["Obliques","Fléchisseurs de hanche"],why:"L’élévation des jambes suspendu entraîne le gainage dynamique et le droit de l’abdomen. La suspension impose de stabiliser les épaules tout en contrôlant le bassin.",steps:["Suspendez-vous à la barre avec les épaules actives.","Gainez avant de lever les jambes.","Montez les genoux ou les jambes sans balancer le buste.","Enroulez légèrement le bassin en haut du mouvement.","Redescendez lentement jusqu’à une suspension contrôlée."],breathing:"Expirez pendant la montée. Inspirez pendant la descente contrôlée.",tempo:{value:"2 - 1 - 3",detail:["2 secondes de montée","1 seconde de contrôle","3 secondes de descente"]},tips:["Commencez genoux fléchis si nécessaire.","Gardez les épaules basses.","Limitez l’amplitude au contrôle du bassin.","Utilisez des sangles si la prise est limitante."],mistakes:["Cambrer le bas du dos.","Balancer les jambes.","Tirer uniquement avec les bras.","Redescendre sans contrôle."] },
];
function format(url:string):MediaFormat{return url.endsWith(".webm")?"OTHER":"WEBP"}
function entries(slug:string){const p=`/media/exercises/${slug}`;return [["THUMBNAIL",`${p}/thumbnail.webp`],["START",`${p}/start.webp`],["MID",`${p}/mid.webp`],["CONTRACTION",`${p}/contraction.webp`],["ANIMATION",`${p}/animation.webm`],["ANIMATION",`${p}/animation.webp`],["ANATOMY_PRIMARY",`${p}/anatomy-primary.webp`],["ANATOMY_SECONDARY",`${p}/anatomy-secondary.webp`]] as const}
async function main(){const report=[];for(const sheet of sheets){const e=await prisma.exercise.findUnique({where:{slug:sheet.slug},select:{id:true}});const assets=entries(sheet.slug);if(!e||assets.some(([,u])=>!existsSync(join(process.cwd(),"public",u)))){report.push({slug:sheet.slug,status:"blocked"});continue}if(apply)await prisma.$transaction(async tx=>{await tx.exercise.update({where:{id:e.id},data:{nameFr:sheet.nameFr,watchDisplayName:sheet.watchDisplayName,equipmentFr:sheet.equipment,movementPatternFr:sheet.pattern,exerciseTypeFr:sheet.type,primaryMusclesFr:sheet.primary,secondaryMuscles:sheet.secondary,whyFr:sheet.why,executionStepsFr:sheet.steps,breathingFr:sheet.breathing,technicalTempo:sheet.tempo as Prisma.InputJsonValue,tipsFr:sheet.tips,commonMistakesFr:sheet.mistakes,technicalSheetStatus:"READY",fallbackThumbnailPath:`/media/exercises/${sheet.slug}/thumbnail.webp`,fallbackImagePath:`/media/exercises/${sheet.slug}/start.webp`,fallbackAnimationPath:`/media/exercises/${sheet.slug}/animation.webp`,primaryAnimationPath:`/media/exercises/${sheet.slug}/animation.webm`}});for(const [i,[role,url]] of entries(sheet.slug).entries()){const anatomy=role.startsWith("ANATOMY");const data={type:role==="THUMBNAIL"?"THUMBNAIL" as const:role==="ANIMATION"?"ANIMATION" as const:"IMAGE" as const,role:role as never,format:format(url),storagePath:url.slice(1),publicUrl:url,mediaStatus:"READY" as const,humanReviewStatus:"APPROVED" as const,characterProfile:anatomy?null:"TRAKNIO_MALE_V1",brandingRequired:!anatomy,isPrimary:role==="THUMBNAIL",isLoop:role==="ANIMATION",sortOrder:i};await tx.exerciseMedia.upsert({where:{exerciseId_role_format:{exerciseId:e.id,role:role as never,format:format(url)}},create:{exerciseId:e.id,...data},update:data})}});report.push({slug:sheet.slug,status:apply?"upserted":"would-upsert"})}console.table(report)}
main().finally(()=>prisma.$disconnect());
